name: Frontend CD

on:
  push:
    branches: ["main"]

defaults:
  run:
    working-directory: ./yigil-admin
permissions:
  contents: read
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: actions/checkout@v3
        run: npm ci
      # npm 테스트 진행
      - name: Run build test
        run: npm run build
      # EC2 인스턴스 접속 및 애플리케이션 실행
      - name: Application Run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST_DEV }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_KEY }}
        
          script: |
            sh ./gitaction-admin-front.sh
